# Site settings
title: Aikido Musashi Halle
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/aikidohalle" # the subpath of your site, e.g. /blog/
url: "http://kennytordeur.github.io" # the base hostname & protocol for your site
include: ['club/overons']
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
